#p1 = int(input(''))
#n1 = int(input(''))
#v1 = float(input(''))
#p2 = int(input(''))
#n2 = int(input(''))
#v2 = float(input(''))
#a1 = input(['int(p1)', 'int(n1)', 'float(v1)'])
#vp = (n1 * v1) + (n2 * v2)
#print('VALOR A PAGAR: R$ {:.2f}'.format(vp))
a1, b1, c1 = input().split()
a2, b2, c2 = input().split()
a1 = int(a1)
b1 = int(b1)
c1 = float(c1)
a2 = int(a2)
b2 = int(b2)
c2 = float(c2)
total = (b1 * c1) + (b2 * c2)
print('VALOR A PAGAR: R$ {:.2f}'.format(total))